communitiesuk/funding-service-design-account-store

- README.md
- core/account.py
- openapi/api.yml
- tests/helpers.py
- tests/test_accounts.py
Fixed account store API naming _"problems"_
> Bau account store update h

- README.md
- requirements-dev.txt
Add previously undocumented dependencies in requirements-dev.txt and documents pre-commit step.
> BAU: add requirements-dev and update readme to include pre-commit step

- requirements-dev.txt
- requirements.in
- requirements.txt
Added psycopg2 to the reqs to allow Postgres to work.
> :heavy_plus_sign: Added psycopg2

- Dockerfile
switch to non-slim image to include GCC dependency
> BAU: fix dockerfile

- README.md
- core/app.py
- manifest.yaml
- requirements-dev.txt
- requirements.in
- requirements.txt
Adds sentry integration using utils function
(Note: slight change from Frontend version https://github.com/communitiesuk/funding-service-design-frontend/pull/146 `SENTRY_DSN` is public, for ease of use with shared workflow but I believe this is OK to be public as per https://docs.sentry.io/product/sentry-basics/dsn-explainer/#dsn-utilization)
> FS-1401: sentry integration

- core/account.py
- openapi/api.yml
- tests/test_accounts.py
Reverts communitiesuk/funding-service-design-account-store#47
> Revert "FS-2003-update-bulk-accounts-functionality"

- .github/workflows/tag-to-zip.yml
Refactor to use shared workflow for tagging
> FS-2172: use shared workflow

- .github/workflows/tag-to-zip.yml
Follow-up to #58 test using branch of action to allowing further testing & debugging
> FS-2172: test on branch of action

- .github/workflows/manual-dev-deploy.yaml
Added environment var for the Assessment url, so that the assessment e2e test doesn't fail to run in the pipeline
N/A
N/A
> BAU - Add env var for Assessment e2e test

- .github/workflows/manual-dev-deploy.yaml
https://digital.dclg.gov.uk/jira/browse/FS-1200
Added assessment store url to enable performance tests for Assessment store.
N/A
N/A
> FS-1200: Enable performance tests for Assessment store to run in the pipelines

- .github/workflows/manual-dev-deploy.yaml
Copied concurrency keys from these PRs to the manual dev deploy yaml file:
https://github.com/communitiesuk/funding-service-design-workflows/pull/43
https://github.com/communitiesuk/funding-service-design-workflows/pull/45
N/A
N/A
> FS 2385: Copy concurrency keys from Workflow repo Account store

- .pre-commit-config.yaml
- app.py
- core/account.py
- db/migrations/env.py
- db/migrations/versions/e355f9c4356b_.py
- tests/test_accounts.py
- tests/test_healthcheck.py
- Add flake8 argument for 120 line length
- Remove black argument for line length
> FS-2689: Change maximum line length to 120

- pytest.ini
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/conftest.py
- tests/test_accounts.py
- tests/test_healthcheck.py
https://digital.dclg.gov.uk/jira/browse/FS-2499
(didn't realise there was a ticket for this already!)
Bumped utils to the latest version in preparation for FS-2291 (improving debug user setup). This brings in th elatest flask-sql-alchemy, which is when we need to update the testing framework so tests converted to use new db seeding method as per other apps.
> FS-2499 bumping to latest utils and fixing tests

- .github/workflows/deploy.yml
- .github/workflows/tag-to-release.yml
* Rearranging the image name to be funding-service-design, not funding-design-service
+ref: FS-3221
+semver: minor
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3221: Fixing wrong order on fsd

- scripts/remove_duplicate_accounts.py
Handle unique constraint "uq_account_azure_ad_subject_id" for azure_ad_subject_id while inserting data
> script improvements unique constraints

- .github/workflows/copilot.yml
- copilot/backend/manifest.yml
- copilot/environments/test/manifest.yml
https://dluhcdigital.atlassian.net/browse/FS-3275
First incarnation of copilot build - doesn't have to work yet - the other apps will have dummy ones.
> FS-3275 Add copilot build (1st pass)

- copilot/environments/dev/manifest.yml
https://dluhcdigital.atlassian.net/browse/FS-3424
Add dev deployment to the copilot environments
> FS-3424 Add dev deployment

- copilot/environments/addons/assessment-import-queue.yml
- copilot/environments/addons/form-uploads.yml
- copilot/environments/addons/funding-service-magic-links.yml
https://dluhcdigital.atlassian.net/browse/FS-3519
Ensure all repos have the same copilot addons as assessment so it doesn't matter where it is created from.
> FS-3519 - Bring all copilot/environments/addons directories into line

- requirements.in
- requirements.txt
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
BAU: bump utils
> BAU: bump utils

- .github/workflows/copilot_deploy.yml
- .github/workflows/deploy.yml
- .github/workflows/environment.yml
- copilot/fsd-account-store/addons/fsd-account-store-cluster.yml
https://dluhcdigital.atlassian.net/browse/FS-3718
Amend the workflows so deployment to AWS dev happens on every commit, and deployment to AWS test happens on merge to master.  Also split out so all environments go via a common module.
> FS-3718 - Amend workflow to deploy automatically

- .github/workflows/copilot_deploy.yml
Use a single source for the version, ensure we run the right post-deploy tests in workflow.
_A brief description of the pull request_
> Bau copilot deploy change

- .github/workflows/copilot_deploy.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
> BAU Concurrent and finalise workflow

- copilot/fsd-account-store/manifest.yml
* Adding uat and production values to copilot config
+ref: FS-3780
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)
- [*] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
> FS-3780 Updating manifest

- .github/workflows/copilot_deploy.yml
- copilot/fsd-account-store/manifest.yml
* Add database migration scripts to the workflow
* Double task count
+ref: FS-3799
+semver: minor
> FS-3799 Updated workflow and copilot manifest

- .github/workflows/deploy.yml
- .github/workflows/manual-dev-deploy.yaml
Updating expired token used in e2e tests
Run e2e tests
> Updated outdated token

- .github/workflows/copilot_deploy.yml
- copilot/fsd-account-store/manifest.yml
- Change `production` to `prod` on copilot configuration
> BAU: Change production to prod on copilot_deploy.yml

- copilot/fsd-account-store/addons/fsd-account-store-cluster.yml
Add bastion sg to the bastion map in copilot
> BAU - Add bastion sg to copilot for prod

- requirements-dev.txt
This reverts commit f419d3debb248f02816e76cc9993b743d7a0dff7.
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
> Revert "Bump bandit from 1.7.4 to 1.7.5 (#148)"

- README.md
The rEADME still referenced an old library that is not used any more - corrected this
> Correcting unit test data description

- .github/workflows/copilot_deploy.yml
_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
_A brief description of the pull request_
> BAU standardise deploy mechanism across envs

- .github/workflows/copilot_deploy.yml
Add app_name to the post-deploy tests
> Bau add app name

- .github/workflows/copilot_deploy.yml
Correcting trigger paths for deployments to prevent need for manual deploys
> fixing trigger paths for deploys

- .env.development
- .flaskenv
- Dockerfile
- Procfile
- app.py
- pytest.ini
- requirements-dev.in
- requirements-dev.txt
- requirements.in
- requirements.txt
- tests/conftest.py
- tests/helpers.py
- tests/test_accounts.py
- tests/test_healthcheck.py
- wsgi.py
https://dluhcdigital.atlassian.net/browse/FS-4561
- Established latest versions of dependencies
- Fixed tests and updated codebase
> FS-4561: Upgrade dependencies

- .github/workflows/copilot_deploy.yml
This files controls Packer, which builds our container images.
> Re-deploy if project.toml changes

- pytest.ini
- requirements-dev.txt
- requirements.in
- requirements.txt
> fs-4647 bump utils
