config/envs/dev.py

Dev config now loads in a sqlite db instead of (trying and failing to) load a Postgres db.

:ambulance: Dev config now using sqlite

---

.github/workflows/manual-dev-deploy.yaml
config/envs/dev.py
config/envs/production.py
manifest.yaml

- Manifest updated to run scripts/run_migrations_pass.py on dev deploy and add funding-service-design-account-store-dev-db as a service
- Manifest updated to rename funding-service-design-account-store-db too funding-service-design-account-store-test-db
- Removed commented sections of un-required code from production config

Fix: Update to enable dev to use Postgres DB

---

core/account.py
openapi/api.yml
tests/test_accounts.py

Updating the bulk accounts endpoint to return metadata by order of account_id provided and return metadata even if multiple instances of the same account_id is given, this is to preserve order and occurrence of who made a score/ comment when using this functionality in assessment to display user info.

FS-2003-update-bulk-accounts-functionality

---

.github/workflows/bump-tag.yml

Use shared workflow to bump tag added in https://github.com/communitiesuk/funding-service-design-workflows/pull/33 Roll-out plan is to test with this merging this PR and roll-out more widely if successful

FS-2172: add workflow to bump tag

---

.github/workflows/tag-to-zip.yml

Follow-up after #59 use `main` version of action after successful testing

FS-2172: use main version of action

---

.github/workflows/tag-to-zip.yml

Change description
Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
[ - ] Unit tests and other appropriate tests added or updated
[ - ] README and other documentation has been updated / added (if needed)
[ - ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
Screenshots of UI changes (if applicable)

add action permission

---

.github/workflows/deploy.yml

https://dluhcdigital.atlassian.net/browse/FS-3075
Allow pre-deploy scripts to run separately for AWS deployments
Tested using deploy to AWS with an ${{ !always() }} flag on.

FS-3075 split aws pre deploy

---

.flaskenv
.github/workflows/manual-dev-deploy.yaml
.pre-commit-config.yaml
README.md
config/envs/dev.py
config/envs/development.py
config/envs/unit_test.py
copilot/environments/addons/funding-service-magic-links.yml
copilot/fsd-account-store/addons/fsd-account-store-cluster.yml
pytest.ini
scripts/remove_duplicate_accounts.py

https://dluhcdigital.atlassian.net/browse/FS-3441
- Added pre-commit 'Yelp/detect-secrets' to prevent committing of secrets to code base
- Ignore false positives by marking them with `pragma: allowlist secret`
- disabled the plugins `HexHighEntropyString` & `Base64HighEntropyString `which tend to detect lot of false positives
- Add a secret/API key/password to any of the file type
For eg. `API_KEY= "125fdfbdjhbj5989"`
- stage the file & commit it.
- Notice the commit is failed with errors.

FS-3441 added yelp hook for secrets

---

copilot/fsd-account-store/addons/fsd-account-store-cluster.yml

https://dluhcdigital.atlassian.net/browse/FS-3457
Add in Bastion's security group into the fsd-account-store DB's inbound rules.
Tested by using the aws ssm connection through bastion and being able to connect into the postgres DB.

FS-3457 - Add Bastion's SG into the ingress into Addon RDS

---

Dockerfile
core/account.py
tests/test_accounts.py

we no longer need a check against valid roles as the deprecated roles are no longer being used. Furthermore if a role is not valid it serves no purpose as our applications check roles validity before allowing access.

remove check against VALID roles configuration

---

.github/workflows/copilot_deploy.yml

Forgot to rearrange the pre-deploy tests dependency to the post-deploy tests dependency so that we can have confidence before pushing to uat/prod
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)

FS-3797 - Adding dependency

---

copilot/fsd-account-store/addons/fsd-account-store-cluster.yml

FS-3880 - Change DB storage-at-rest to be encrypted as a result of PEN testing
NOTE: Deletes the database so data re-migration is required.

FS-3880 - Encrypt DBs

---

copilot/fsd-account-store/manifest.yml

-FS-4411: Overprovision instance
Change description
Reduce the number of instance to 1 in Dev and change the ECS launch_type to Fargate-spot.
Unit tests and other appropriate tests added or updated
README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
_Will check after deployment by logging into the ECS console and view the service and instance configuration

FS-4411:Over-provision instance and change to Fargate-spot

---

core/account.py
openapi/api.yml
tests/conftest.py
tests/test_accounts.py

Added an API endpoint to be able to retrieve users that have roles (assessors, commenters) related to a fund. 
N/A
N/A

Added API endpoint to retrieve users for fund

---

openapi/api.yml
requirements-dev.txt
requirements.txt

- Fix a typo in the openapi spec
- Fix an inconsistency in sqlalchemy between `requirements.txt` (sqlqlachemy==2.0.31) and `requirements-dev.txt` (sqlalchemy==2.0.30).

A few miscellaneous fixes

---

core/account.py
openapi/api.yml
tests/test_accounts.py

On post-award we need a way to list all accounts with the (new) SECTION_151 role that are under a specific email domain.
This new endpoint provides that core functionality.
https://dluhcdigital.atlassian.net/browse/FPASF-477
* Enable the swagger UI by updating `app.py` to:
```
connexion_app = connexion.FlaskApp(
__name__,
specification_dir=Config.FLASK_ROOT + "/openapi/",
swagger_ui_options=SwaggerUIOptions(swagger_ui_path="/docs"),
)
```
* Run the app and go to http://localhost:3003/docs/#/accounts/core.account.search_accounts
* Use the swagger UI to test the new endpoint.

Add accounts search endpoint

---

db/migrations/env.py
pytest.ini
tests/conftest.py

Turns all warnings into errors so that they can be caught early and developers are required to handle them (either by fixing the code or explicitly ignoring the error).
This ignores a few errors from our dependencies, and fixes others, such as:
- changing `get_engine()` to `engine`
- ignoring `connexion` json schema and validation warnings
- changing scope of the pytest connexion flask fixture to `session` instead of `function`  
Are there any warnings?

FPASF-490: Turn warnings into errors when running pytest

---

.github/workflows/copilot_deploy.yml

- Due to the changes made in the workflows repo, basic auth secrets would now be passed on where post_deploy workflow is being re-used

FLS-795: Pass basic auth secrets to workflow

---

copilot/fsd-account-store/manifest.yml

This is because the `recreate` deployment method leads to downtime, which can cause tests to flake. It is not any faster than a normal deployment, and causes tests to break. I am not sure why it was chosen to begin with.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling

Turn off recreate deploys in test environment

---

.github/workflows/copilot_deploy.yml

These paths control whether or not the workflow runs on push, including to PRs.
Unless these are kept perfectly up-to-date, then sometimes we'll not run tests on PRs that should have them run.
See https://github.com/communitiesuk/funding-service-design-account-store/pull/258 which changes pyproject.toml and uv.lock. This should definitely be tested but isn't. I could add the files, but that just pushes the problem into the future. A few "wasted" runs are better than missing one "required" run, IMO. Let's do the safe thing here.

Remove workflow exceptions

---

.vscode/launch.json
invoke.yaml
tasks.py

Adds a seeding script to the account-store to setup the account `lead_assessor@example.com` with roles for the dummy fund, if they don't already exist.

Adding lead assessor account seeding script

---

copilot/fsd-account-store/manifest.yml

Trace all requests on pre-prod
The production value is based on utils default from: https://github.com/communitiesuk/funding-service-design-utils/blob/b65c285328847640f8622c368595938b60e44d02/fsd_utils/sentry/init_sentry.py#L19C59-L19C63 we could possibly increase this in future, but previously a combination of bot traffic and looping errors have used all our quota.
Traces should increase post-deployment

FSPT-123: Trace all requests on pre-prod
